/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.Doctor;

import Model.Doctor;
import Ui.Patient.*;
import Model.DoctorDirectory;
import Model.Hospital;
import Model.HospitalDirectory;
import Model.Patient;
import Model.PatientDirectory;
import Model.Person;
import Model.PersonDirectory;
import javax.swing.JOptionPane;

/**
 *
 * @author risha
 */
public class DoctorSystemCreateFormJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalSystemCreateFormJPanel
     */
    PersonDirectory persondirectory;
    DoctorDirectory doctordirectory;
    HospitalDirectory hospitaldirectory;
    PatientDirectory patientdirectory;
    public DoctorSystemCreateFormJPanel(PersonDirectory persondirectory,PatientDirectory patientdirectory,HospitalDirectory hospitaldirectory,DoctorDirectory doctordirectory) {
        initComponents();
        this.persondirectory = persondirectory;
        this.patientdirectory = patientdirectory;
        this.hospitaldirectory = hospitaldirectory;
        this.doctordirectory = doctordirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtState = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        SubmitBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtHospitalId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        txtHospitalName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtSsnId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnFetchPerson = new javax.swing.JButton();
        txtCity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnFetchHospital = new javax.swing.JButton();

        jLabel6.setText("City");

        jLabel7.setText("Community");

        jLabel8.setText("State");

        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Mobile No");

        jLabel5.setText("Password");

        jLabel12.setText("Hospital Name");

        jLabel10.setText("Email");

        jLabel11.setText("Hospital ID");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Create Form");

        jLabel13.setText("SSN ID");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        btnFetchPerson.setText("Fetch Details");
        btnFetchPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFetchPersonActionPerformed(evt);
            }
        });

        jLabel3.setText("Gender");

        jLabel4.setText("Age");

        btnFetchHospital.setText("Fetch Details");
        btnFetchHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFetchHospitalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(SubmitBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail)
                            .addComponent(txtPassword)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName)
                            .addComponent(txtGender)
                            .addComponent(txtAge)
                            .addComponent(txtCity)
                            .addComponent(txtCommunity)
                            .addComponent(txtState, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMobile)
                            .addComponent(txtHospitalId)
                            .addComponent(txtHospitalName)
                            .addComponent(txtSsnId)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFetchPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFetchHospital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtHospitalId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFetchHospital))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSsnId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFetchPerson))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(SubmitBtn)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        long hospitalid = Long.parseLong(txtHospitalId.getText());
        String hospitalname = txtHospitalName.getText();
        long ssnid = Long.parseLong(txtSsnId.getText());
        String name = txtName.getText();
        String gender = txtGender.getText();
        int age = Integer.parseInt(txtAge.getText());
        String city = txtCity.getText();
        String community = txtCommunity.getText();
        String state = txtState.getText();
        long mobile = Long.parseLong(txtMobile.getText());
        String email = txtEmail.getText();
        String password = txtPassword.getText();

        //        if (!Pattern.matches("^([1-9]{6})$", txtSsn.getText()))
        //         {
            //             JOptionPane.showMessageDialog(null, "Enter valid 6 digit employee id", "Error", JOptionPane.ERROR_MESSAGE);
            //             SubmitBtn.setEnabled(false);
            //         }
        //        else if (!Pattern.matches("^\\d+$", txtAge.getText()))
        //         {
            //             JOptionPane.showMessageDialog(null, "Age cannot be negative", "Error", JOptionPane.ERROR_MESSAGE);
            //             SubmitBtn.setEnabled(false);
            //         }
        //        else if (!Pattern.matches("^(1[89]|2[0-9]|3[0-9]|4[0-9]|5[0-9]|6[0-5])$", txtAge.getText()))
        //         {
            //             JOptionPane.showMessageDialog(null, "Age should be between 18 to 65", "Error", JOptionPane.ERROR_MESSAGE);
            //             SubmitBtn.setEnabled(false);
            //         }
        //        else if (!Pattern.matches("^^(?:male|Male|MALE|female|Female|FEMALE)$",txtGender.getText()))
        //        {
            //          JOptionPane.showMessageDialog(null, "Gender has to be male or female", "Error", JOptionPane.ERROR_MESSAGE);
            //          SubmitBtn.setEnabled(false);
            //        }
        //        else if (!Pattern.matches("^[1-9]{1}[0-9]{9}", txtMobile.getText()))
        //         {
            //             JOptionPane.showMessageDialog(null, "Enter valid 10 digit number", "Error", JOptionPane.ERROR_MESSAGE);
            //             SubmitBtn.setEnabled(false);
            //         }
        //        else if (!(Pattern.matches("^[a-zA-Z0-9]*+[@]{1}+[a-zA-Z0-9]*+[.]{1}+[a-zA-Z0-9]*+$", txtEmail.getText()))) {
            //            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
            //            SubmitBtn.setEnabled(false);
            //            }
        //        else {

            Doctor docobj = doctordirectory.addDoctor();

            docobj.setName(name);
            docobj.setGender(gender);
            docobj.setAge(age);
            docobj.setCity(city);
            docobj.setCommunity(community);
            docobj.setState(state);
            docobj.setEmail(email);
            docobj.setMobile(mobile);
            docobj.setDoctor_password(password);
            docobj.setHospital_id(hospitalid);
            docobj.setHospital_name(hospitalname);
            docobj.setSSN_id(ssnid);

            JOptionPane.showMessageDialog(this,"New patient added to the Directory");

            txtName.setText("");
            txtAge.setText("");
            txtGender.setText("");
            txtCity.setText("");
            txtState.setText("");
            txtCommunity.setText("");
            txtEmail.setText("");
            txtMobile.setText("");
            txtPassword.setText("");
            //}
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void btnFetchPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFetchPersonActionPerformed
        // TODO add your handling code here:
        boolean flag = false;
        for(Person per : persondirectory.getPersonDirectory())
        {
            if ((String.valueOf(per.getSSN_id()).equals(txtSsnId.getText())))
            {
                txtName.setText(per.getName());
                txtAge.setText(String.valueOf(per.getAge()));
                txtGender.setText(per.getGender());
                txtCity.setText(per.getCity());
                txtState.setText(per.getState());
                txtCommunity.setText(per.getCommunity());
                txtMobile.setText(String.valueOf((per.getMobile())));
                txtEmail.setText(per.getEmail());

                flag = false;

                txtSsnId.setEnabled(false);
                txtName.setEnabled(false);
                txtGender.setEnabled(false);
                txtAge.setEnabled(false);
                txtCity.setEnabled(false);
                txtCommunity.setEnabled(false);
                txtState.setEnabled(false);
                txtMobile.setEnabled(false);
                txtEmail.setEnabled(false);
                break;
            }
            else
            {
                flag = true;
            }
        }
        if (flag == true)
        {
            JOptionPane.showMessageDialog(this, "Person doesn't exits");
        }
    }//GEN-LAST:event_btnFetchPersonActionPerformed

    private void btnFetchHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFetchHospitalActionPerformed
        boolean flag = false;
        for(Hospital hospital : hospitaldirectory.getHospitalDirectory())
        {
            if ((String.valueOf(hospital.getHospital_id()).equals(txtHospitalId.getText())))
            {
                txtHospitalName.setText(String.valueOf(hospital.getHospital_name()));

                flag = false;

                txtHospitalId.setEnabled(false);
                txtHospitalName.setEnabled(false);
                break;
            }
            else
            {
                flag = true;
            }
        }
        if (flag == true)
        {
            JOptionPane.showMessageDialog(this, "Hospital doesn't exits");
        }
    }//GEN-LAST:event_btnFetchHospitalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JButton btnFetchHospital;
    private javax.swing.JButton btnFetchPerson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtHospitalId;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSsnId;
    private javax.swing.JTextField txtState;
    // End of variables declaration//GEN-END:variables
}
